project:
  type: book
  output-dir: _site

book:
  title: "Learning SQL Notes"
  author: "Emanuel Quintana"
  chapters:
    - index.qmd
    - part: "Learning SQL (Beaulieu)"
      chapters:
        - beaulieu/notas.qmd
    - part: "SQL Queries for Mere Mortals (Viescas)"
      chapters:
        - viescas/notas.qmd
    - part: "Using SQLite (Kreibich)"
      chapters:
        - kreibich/notas.qmd

format:
  html:
    theme: cosmo
    toc: true
  pdf:
    documentclass: scrbook
